version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: "npm i"
      - cypress/run:
          requires:
            - cypress/install
          group: "Webmail test"
          start: "npx cypress run --spec cypress/integration/webmail/inbox.spec.ts"