version: 2.1

parameters:
  default_job_env:
    type: string
    default: "cypress"

orbs:
  # Continuation orb makes it easy to send
  # the generated config to the continuation API.
  continuation: circleci/continuation@0.2.0
  # Node orb used to build our config app in a Node environment.
  node: circleci/node@4.7.0
setup: true
jobs:
  generate-config:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: .circleci/dynamic
      - when:
          condition:
           equal: [ << pipeline.parameters.default_job_env >>, "cypress" ]
          steps: 
          - run:
              name: Check env param
              command: |
                echo << pipeline.parameters.default_job_env >>
          - run:
              name: Generate config
              command: |
                DEFAULT_JOB=1 node .circleci/dynamic/app.js
          - continuation/continue:
              configuration_path: ./dynamicConfig.yml
      - when:
          condition:
           equal: [ << pipeline.parameters.default_job_env >>, "webmail" ]
          steps: 
          - run:
              name: Check env param
              command: |
                echo << pipeline.parameters.default_job_env >>
          - run:
              name: Generate config
              command: |
                DEFAULT_JOB=0 node .circleci/dynamic/app.js
          - continuation/continue:
              configuration_path: ./dynamicConfig.yml
    
workflows:
  conditional-workflow:
    when: << pipeline.parameters.default_job_env >>
    jobs:
      - generate-config