version: 2.1

executors:
  chrome-only:
    docker:
      - image: "cypress/browsers:node16.13.0-chrome95-ff94"
    resource_class: medium

linux-workflow: &linux-workflow
  jobs:
    # Run Webmail E2E tests in desktop Chrome
    - cypress/run:
        name: "Linux - Chrome - Webmail e2e - Desktop"
        steps:
          - run:
              name: Install deps
              command: npm i
          - run:
              name: Cypress info
              command: npx cypress -v
          - run:
              name: "Run webmail e2e"
              command: npm run e2e:webmail

workflows:
  linux:
    <<: *linux-workflow