version: 2.1

executors:
  chrome-only:
    docker:
      - image: "cypress/browsers:node16.13.0-chrome95-ff94"
    resource_class: medium

jobs:
  cypress-tests:
    executor: chrome-only
    steps:
      - checkout: {}
      - run:
          command: npm install
          name: NPM Install
      - run:
          command: npx cypress -v
          name: Check Cypress
      - run:
          command: npm run e2e:webmail
          name: Run webmail e2e tests
workflows:
  myWorkflow:
    jobs:
      - cypress-tests: {}